Map<String, String> foodImages = {
  'Default': 'default.png',
  'Dim Sum': 'dimSum.jpg',
  'Cafe': 'cafe.jpg',
  'Burger': 'cheeseburger.png',
  'American': 'cheeseburger.png',
  'Chinese': 'chinese.jpg',
  'Coffee and Tea': 'coffee.jpg',
  'Crepes': 'crepes.jpg',
  'French': 'french.jpg',
  'Indian': 'indianFood.jpg',
  'Pakistani': 'indianFood.jpg',
  'Italian': 'Italian.jpg',
  'Japanese': 'japanese.jpg',
  'Latin American': 'latinAmerican.jpg',
  'Tapas': 'latinAmerican.jpg',
  'Mexican': 'mexican.jpg',
  'Moroccan': 'moroccanFood.jpg',
  'Sushi': 'sushu.jpg',
  'Thai': 'thai.jpg',
  'Vietnamese': 'VietnameseFood.jpg',
  'Pizza': 'pizza.png',
  'Bakery': 'bakery.jpg',
  'Beverages': 'beverages.jpg',
  'Juices': 'juice.jpg',
  'Donuts': 'donuts.jpg',
  'Frozen Yogurt': 'frozenYogurt.jpg',
  'Ice Cream': 'iceCream.jpg',
  'Sandwich': 'sandwich.jpg',
  'Bubble Tea': 'bubbleTea.jpg',
};